### ISSUE TITLE
Selecting a Example is slow in Linux (IEP-709)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/idf-eclipse-plugin#541]
When you say: 

"Create a new IDF Project" 

and want to use one of the Examples as a Template, 

this Selection Dialog is Very slow in Linux, and leads somtimes to crash of Eclipse. 

while same is fast in Windows.

**Comment by franz-ms-muc** [comment]
another experience: 

if you use the "filter text" it is fast. 

if you navigate the Folders it is slow.

**Comment by sigmaaa** [comment]
Hi @franz-ms-muc,

I was not able to reproduce this issue on my virtual box ubuntu. Selection can be slow due to low heap memory value. It's possible to change this value for eclipse in the eclipse.ini file, arguments are -Xms and -Xmx. 
Also, what can help to fix the issue is the `hs_err_pidXXXXX.log` file, which is generated, when eclipse crashed. You can find more details [here](https://wiki.eclipse.org/FAQ_Where_can_I_find_that_elusive_.log_file%3F).
Could you provide us with an error log so we can better understand what could be the cause? Thank you

**Comment by franz-ms-muc** [comment]
I will make.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by diplfranzhoepfinger** [comment]
i tested on a newly installed Ubuntu 22.04 LTS, and the issue is gone.

**Comment by diplfranzhoepfinger** [comment]
Hi, 

the issue is Back on Ubuntu 23.10

**Comment by diplfranzhoepfinger** [comment]
logfile here: 

https://gist.github.com/diplfranzhoepfinger/39b97d7a3392195f7cbf0066389e5c22
